# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php


# list any PHP version you want to test against
php:
  - 5.6
  - 7.1

install:
  - composer self-update
  - composer update --prefer-dist

# omitting "script:" will default to phpunit
script: php test/Checkfront.php

notifications:
  email:
    recipients:
    - jason+ci@htmlgraphic.com
