# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php


# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

install:
  - composer self-update
  - composer update --prefer-dist

# omitting "script:" will default to phpunit
script: php test/Checkfront.php

notifications:
  email:
    recipients:
    - jason+ci@htmlgraphic.com
    on_success: change
    on_failure: change